package admin_test

import (
	"fmt"
	"testing"

	"github.com/qor/qor"
	"github.com/qor/qor/admin"

	_ "github.com/mattn/go-sqlite3"
)

// Template helpers test

func TestLinkTo(t *testing.T) {
	context := &admin.Context{Admin: Admin}

	link := context.LinkTo("test link", "/link")

	if link != "<a href=\"/link\">test link</a>" {
		t.Error("link not generated by LinkTo")
	}
}

func TestUrlForAdmin(t *testing.T) {
	context := &admin.Context{Admin: Admin}

	rootLink := context.UrlFor(Admin)

	if rootLink != "/admin" {
		t.Error("Admin link not generated by UrlFor")
	}
}

func TestUrlForResource(t *testing.T) {
	context := &admin.Context{Admin: Admin}
	user := Admin.GetResource("user")

	userLink := context.UrlFor(user)

	if userLink != "/admin/user" {
		t.Error("resource link not generated by UrlFor")
	}
}

func TestUrlForResourceName(t *testing.T) {
	user := &User{Name: "test"}
	db.Create(&user)

	context := &admin.Context{Admin: Admin, Context: &qor.Context{}}
	context.SetDB(&db)

	userLink := context.UrlFor(user)

	if userLink != "/admin/user/"+fmt.Sprintf("%v", user.Id) {
		t.Error("resource link not generated by UrlFor")
	}
}
